### ISSUE TITLE
BBChat 1.7.10 doesn't offer true sync

### ISSUE THREAD

**Issue by superhealing** [breakinblocks/BBChat#1]
I use recently in a server where the version sits 1.7.10, pure forge with couple additions mods.
With proper configuration, including last 3 check boxes on developer portal (+ tokens ids). 
There is connection between discord and server, but in one way, server to discord, but not discord to server.
Logs doesn't output anything significant sadly.
Almost forgot to mention, in past did indeed offer true sync, i'm assuming something discord did change APIs.
I suppose is a bug, otherwise i don't know where is wrong with my configuration.

**Comment by BlueAgent** [comment]
Hmm. I can't seem to reproduce this on a 1.7.10 server.

![2022-11-28_22h58m36s768_Discord](https://user-images.githubusercontent.com/630920/204309715-c6ad8ef8-9d72-438d-8d0b-af800f462211.png)

Can you try the latest version of BBChat to see if it works? (v0.0.21, but v0.0.20 seems to work for me as well.)

Also does the bot have the correct permissions on the server (Read Messages)?
Maybe try giving it the same roles as a normal member of the server as a test. (Need to add a check and log for this in BBChat at some point.)

It sounds like you have the message content intent enabled so it shouldn't be that.

As a side note JDA will need to be migrated to v5 at some point. I've done it for my Discord bot but will need to do it for this project as well.

**Comment by BlueAgent** [comment]
I've added some warnings messages for configuration in [v0.0.22](https://github.com/breakinblocks/BBChat/releases/tag/v0.0.22) as well as updated to JDA v5 so hopefully that helps fix the problem.

Let us know if it works or not when you can.
Feel free to re-open if it's still not working and the new warnings don't help to address it.
It may be easier to discuss this on [Discord](https://discord.com/invite/UBfM9rx).
